apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config
data:
  # property-like keys; each key maps to a simple value
  swagger_server_uri: {{ .Values.config.swagger_server_uri }}
  log_level: {{ .Values.config.log_level }}
  prefix: {{ .Values.config.service_prefix }}
  db_user: {{ .Values.postgresql.auth.username }}
  db_name: {{ .Values.postgresql.auth.database }}
