FROM rust:1.83.0 AS builder

# Install dependecies first for caching.
WORKDIR /usr/src/cs-mock
ADD Cargo.* . 
#RUN mkdir ./src
RUN echo "fn main() {}" > ./dummy.rs
RUN sed -i 's#src/main.rs#dummy.rs#' Cargo.toml
RUN cargo build --release

# Install
ADD . .
RUN cargo build --release

FROM mpspdz:shamir

RUN apt update
RUN apt install -y gettext-base libc6

# Setup and run cs-mock
COPY --from=builder /usr/src/cs-mock/target/release/cs-mock /usr/local/bin/cs-mock
CMD ["cs-mock"]
