services:
  csmock:
    image: cs_mock:latest
    platform: linux/amd64
    environment:
      COMPUTATION_RESULT: "[120,324,5235]"
      SWAGGER_SERVER_URI: "${PUBLIC_SERVICE_URI}:${CLIENT_SERVICE_PORT:-8085}"
    ports:
      - "8085:80"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
    networks:
      default:
        aliases:
          - ephemeral-generic.default.csmock

  party2:
    image: cs_mock:latest
    platform: linux/amd64
    environment:
      COMPUTATION_RESULT: "[120,324,5235]"
      SWAGGER_SERVER_URI: "${PUBLIC_SERVICE_URI}:${CLIENT_SERVICE_PORT:-8085}"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
    networks:
      - default

networks:
  default:
