service:
  type: ClusterIP
  port: 80
  loadBalancerIP: 172.18.3.128

deployment:
  image: ghcr.io/glaciation-heu/sap-uc3/client_service:0.1.2
  pullSecret: ""
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits: 
      memory: "128Mi"
      cpu: "500m"

config:
  swagger_server_uri: ""
  coordinator_uri: "http://coordination-service.svc.cluster.local"
  log_level: info
  service_prefix: ""
