apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config
  annotations:
    # helm deletes the object is present due to above "if not" condition
    # add annotation to keep the object
    # helm.sh/resource-policy: keep
data:
  # property-like keys; each key maps to a simple value
  swagger_server_uri: {{ .Values.config.swagger_server_uri }}
  log_level: {{ .Values.config.log_level }}
  prefix: {{ .Values.config.service_prefix }}
  coordinator_uri: {{ .Values.config.coordinator_uri }}
