#apiVersion: v1
#kind: ConfigMap
#metadata:
#    name: csmock-coredns-plugin
#    namespace: kube-system
#data:
#  ephemeral-generic.conf: |
#    rewrite {
#        name ephemeral-generic.default.{{ include "service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local {{ include "service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
#    }