---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port  | default 80 }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "service.fullname" . }}