
services:
  test_database:
    container_name: test_database
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
    ports:
      - "5432:5432"
    volumes:
      - db-testing:/var/lib/postgresql/data:rw

  test_env:
    image: rust:1.83.0
    volumes:
      - .:/application:rw
    working_dir: /application
    depends_on:
      - test_database
    command: ["cargo", "test", "--test", "*"]
    environment:
      DATABASE_USER: testing
      DATABASE_PASSWD: testing
      DATABASE_HOST: test_database
    
volumes:
  db-testing: