namespace: default
service:
  type: ClusterIP
  port: 80
  loadBalancerIP: 172.18.3.129

deployment:
  image: ghcr.io/glaciation-heu/sap-uc3/coordination_service:0.1.2
  pullSecret: ""
  replicas: 1
  port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits: 
      memory: "128Mi"
      cpu: "500m"

config:
  # Service uri for the swagger server.
  swagger_server_uri: ""
  log_level: info
  service_prefix: ""

#DB configuration
postgresql:
  auth:
    username: coord
    password: coord
    database: coorddb
  primary:
    podSecurityContext:
        enabled: false
        fsGroup: ""
    containerSecurityContext:
        enabled: false
        runAsUser: "auto"

readReplicas:
    podSecurityContext:
        enabled: false
        fsGroup: ""
    containerSecurityContext:
        enabled: false
        runAsUser: "auto"

volumePermissions:
    enabled: false
    securityContext:
        runAsUser: "auto"
