service:
  type: ClusterIP
  port: 80
  clusterIP: "10.96.123.45"

deployment:
  image: ghcr.io/glaciation-heu/sap-uc3/cs_mock:latest
  pullSecret: ""
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits: 
      memory: "128Mi"
      cpu: "500m"

config:
  swagger_server_uri: ""
  log_level: info
  service_prefix: ""
