{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-collab-comp-service
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.prefix }}/client
        backend:
          service:
            name: {{ .Release.Name }}-client-service
            port:
              number: 80
      - pathType: Prefix
        path: {{ .Values.ingress.prefix }}/coord
        backend:
          service:
            name: {{ .Release.Name }}-coordination-service
            port:
              number: 80
      - pathType: Prefix
        path: {{ .Values.ingress.prefix }}/csmock
        backend:
          service:
            name: {{ .Release.Name }}-csmock
            port:
              number: 80
{{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
  - host: ephemeral-generic.default.{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.prefix }}/csmock
        backend:
          service:
            name: {{ .Release.Name }}-csmock
            port:
              number: 80
{{- end }}
{{- end -}}