{{- if .Values.smoketesting.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "smoketesting.service.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  csconfig: |
    {
      "prime" : "198766463529478683931867765928436695041",
      "r" : "141515903391459779531506841503331516415",
      "noSslValidation" : true,
      "providers" : [ {
        "amphoraServiceUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/0/amphora",
        "castorServiceUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/0/castor",
        "ephemeralServiceUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/0",
        "id" : 1,
        "baseUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/0/"
      }, {
        "amphoraServiceUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/1/amphora",
        "castorServiceUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/1/castor",
        "ephemeralServiceUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/1",
        "id" : 2,
        "baseUrl" : "http://{{ include "csmock.service.domainname" . }}/csmock/1/"
      } ],
      "rinv" : "133854242216446749056083838363708373830"
    }
{{- end -}}