name: Unittesting

on:
  workflow_call:

jobs:
  unittest:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      # save the tag as an environment variable
      - name: Set Environment variable
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}">>$GITHUB_ENV

      - name: Save Git Tag to Artifact
        run: echo "${{ env.GIT_TAG }}" > git_tag.txt

      - name: Upload Git Tag Artifact
        uses: actions/upload-artifact@v4
        with:
          name: git_tag
          path: git_tag.txt

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Client service cargo caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./client_service -> target"
          shared-key: client-cargo-cache

      - name: Run unit tests for clinet-service
        working-directory: ./client_service
        run: cargo test --lib

      - name: Coordination service cargo caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./coordination_service -> target"
          shared-key: coord-cargo-cache

      - name: Run tests for coordination-service
        working-directory: ./coordination_service
        run: cargo test --lib
