name: Coord Integration Testing

on:
  workflow_call:

jobs:
  coord-int-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Coordination service cargo caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./coordination_service -> target"
          shared-key: coord-cargo-cache

      - name: run integration tests for Coordination Service
        working-directory: ./coordination_service
        env:
          DATABASE_USER: postgres
          DATABASE_PASSWD: password
          DATABASE_HOST: localhost
        run: cargo test --test "*"
