name: Build and publish Coordination service, Mock and Smoketesting images.

on:
  workflow_call:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-coord-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Download Git Tag Artifact
        uses: actions/download-artifact@v4
        with:
          name: git_tag

      - name: Read Git Tag
        id: read_git_tag
        run: echo "GIT_TAG=$(<git_tag.txt)" >> $GITHUB_ENV


# Coordination-Service
      - name: Build and push Docker image for coordination_service
        id: push-coordination-service
        uses: docker/build-push-action@v6
        with:
          context: ./coordination_service
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/glaciation-heu/sap-uc3/coordination_service:${{ env.GIT_TAG }}
            ghcr.io/glaciation-heu/sap-uc3/coordination_service:latest

# CS-Mock
      - name: Build and push Docker image for cs-mock
        id: push-mock
        uses: docker/build-push-action@v6
        with:
          context: ./cs_mock
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
           ghcr.io/glaciation-heu/sap-uc3/cs_mock:${{ env.GIT_TAG }}
           ghcr.io/glaciation-heu/sap-uc3/cs_mock:latest
      
# Smoketesting
      - name: Build and push Docker image for smoketesting
        id: push-smoketesting
        uses: docker/build-push-action@v6
        with:
          context: ./smoketesting
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/glaciation-heu/sap-uc3/smoketesting:${{ env.GIT_TAG }}
            ghcr.io/glaciation-heu/sap-uc3/smoketesting:latest
