name: Client Integration testing

on:
  workflow_call:

jobs:
  client-int-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: coord
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      coordination_service:
        image: ghcr.io/glaciation-heu/sap-uc3/coordination_service:latest
        ports:
          - 8080:8080
        env:
          SWAGGER_SERVER_URI: "http://localhost"
          DATABASE_USER: postgres
          DATABASE_DBNAME: coord
          DATABASE_PASSWD: password
          DATABASE_HOST: postgres
          LOG_LEVEL: debug
          SERVICE_PORT: 8080

      csmock:
        image: ghcr.io/glaciation-heu/sap-uc3/cs_mock:latest 
        ports:
          - 80:80
        env:
          SWAGGER_SERVER_URI: "http://localhost"
          LOG_LEVEL: debug

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: docker ps
        run: docker ps

      - name: get IP address of csmock
        id: get-csmock-ip
        run: |
          CSMOCK_ID="$(docker ps | grep cs_mock | head -n1 | awk '{print $1;}')"
          echo $CSMOCK_ID
          echo "CSMOCK_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CSMOCK_ID)" >> "$GITHUB_OUTPUT"

      - name: Add csmock to hosts
        run: |
          echo "127.0.0.1 ephemeral-generic.default.csmock" | sudo tee -a /etc/hosts
          echo "127.0.0.1 csmock" | sudo tee -a /etc/hosts

      - name: Add csmock service alias to coordination_service manually
        run: |
          COORD_ID="$(docker ps | grep coordination_service | head -n1 | awk '{print $1;}')"
          docker exec $COORD_ID /bin/sh -c 'echo "${{ steps.get-csmock-ip.outputs.CSMOCK_IP }} ephemeral-generic.default.csmock" | tee -a /etc/hosts'

      - name: Test connection to service using alias
        run: |
          curl -v http://csmock:80/ping

      - name: Client service cargo caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./client_service -> target"
          shared-key: client-cargo-cache

      - name: Download cs.jar
        run: |
          sudo curl -o /usr/local/cs.jar -L https://github.com/carbynestack/cli/releases/download/cli-v0.4.1/cli-0.4.1.jar
          sudo chmod 666 /usr/local/cs.jar

      - name: Install java runtime
        run: |
          sudo apt update
          sudo apt install openjdk-17-jre --yes

      - name: run integration tests for Client Service
        working-directory: ./client_service
        env:
          COORDINATOR_URI: "http://localhost:8080"
        run: cargo test --test "*"
