name: AllUnitTests
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  call-unittest:
    uses: ./.github/workflows/01-unittesting.yml
      
  call-coord-int-test:
    needs:
      - call-unittest
    uses: ./.github/workflows/02-coord-int-test.yml

  call-build-and-push-coord-image:
    needs:
      - call-coord-int-test
    uses: ./.github/workflows/03-build-and-push-coord-image.yml

  call-client-int-test:
    needs:
      - call-build-and-push-coord-image
    uses: ./.github/workflows/04-call-client-int-test.yml

  call-build-and-push-client-image:
    needs:
      - call-client-int-test
    uses: ./.github/workflows/05-build-and-push-client-image.yml

  call-publish-charts:
    needs:
      - call-build-and-push-client-image
      - call-build-and-push-coord-image
    uses: ./.github/workflows/06-publish-charts.yml
